### ISSUE TITLE
Recreating t-SNE plot guidance

### ISSUE THREAD

**Issue by JonathanMathews** [takahikof/ShapeAutoTranscoder#2]
Hello! I trained the SAT model on the ModelNet10 dataset, and now have a trained model with a checkpoint file, as expected. Now, I am trying to recreate the t-SNE plot from the SAT paper. However, there is not a lot of guidance for how the t-SNE plot was created. Do I have to write a small script to run the files through the model and explicitly pull out the embedded features? Then pass these embedded features through a t-SNE algorithm? Or is there a premade function that the authors used for their t-SNE plot that I can call and streamline the process? Thank you for any help!

**Comment by takahikof** [comment]
Unfortunately, the script for creating the t-SNE plot in the paper is not contained in this repository. You need to create your own script/code for t-SNE visualization.
